language: node_js
node_js:
  - "lts/*"
cache:
  directories:
    - "node_modules"

install:
  - npm install

script:
  - npm run-script build

after_success:
  - source ./scripts/deploytarget.sh

before_deploy:
  - pip install --user awscli

deploy:
  provider: script
  script: ~/.local/bin/aws s3 sync dist s3://${DEPLOY_TARGET} --delete --region=us-east-1
  skip_cleanup: true
  on: 
    condition: -n "${DEPLOY_TARGET}"
    all_branches: true # Leave to the above condition the decision whether deploying

# TODO S3 deploy doesn't sync the directory, only adds new files: use AWS CLI to sync
