language: node_js
node_js:
  - "lts/*"
cache:
  directories:
    - "node_modules"

env:
  - PROD_TAG_REGEXP="^rel(ease)?-.+$" #Regexp for release (deploy to Prod) tags

install:
  - npm install

script:
  - npm run-script build

before_deploy:
  - pip install --user awscli

deploy:
  # deploy master to Staging
  - provider: script
    script: ~/.local/bin/aws s3 sync dist s3://${STAGING_BUCKET} --delete --region=${STAGING_BUCKET_REGION} && ~/.local/bin/aws cloudfront create-invalidation --distribution-id ${STAGING_DISTRIBUTION_ID} --paths /*
    skip_cleanup: true
    on:
      branch: master

  # deploy tags matching rel-* or release-* to Production
  - provider: script
    script: ~/.local/bin/aws s3 sync dist s3://${PROD_BUCKET} --delete --region=${PROD_BUCKET_REGION} && ~/.local/bin/aws cloudfront create-invalidation --distribution-id ${PROD_DISTRIBUTION_ID} --paths /*
    skip_cleanup: true
    on:
      tags: true
      condition: $TRAVIS_TAG =~ $PROD_TAG_REGEXP
