sudo: false
language: node_js
branches:
  only:
  - master
  except:
  - "/^v\\d+\\.\\d+\\.\\d+$/"
notifications:
  email: false
node_js:
- '6'
## Encryption before deploying
# travis encrypt --add deploy.secret_access_key
## Security credentials
# https://console.aws.amazon.com/iam/home?#security_credential
deploy:
  provider: s3
  access_key_id: "YOUR AWS ACCESS KEY"
  secret_access_key: "YOUR AWS SECRET KEY"
  bucket: "S3 Bucket"