language: node_js
node_js:
  - "lts/*"
cache:
  directories:
    - "node_modules"

env:
  - PROD_TAG_REGEXP="^rel(ease)?-.+$" #Regexp for release (deploy to Prod) tags

install:
  - npm install

script:
  - npm run-script build

before_deploy:
  - pip install --user awscli

deploy:
  # deploy master to Staging
  - provider: script
    script: scripts/deploy.sh staging
    skip_cleanup: true
    on:
      branch: master

  # deploy tags matching rel-* or release-* to Production
  - provider: script
    script: scripts/deploy.sh production
    skip_cleanup: true
    on:
      tags: true
      condition: $TRAVIS_TAG =~ $PROD_TAG_REGEXP
